### PR TITLE
Remove .com from placeholder

### PR DESCRIPTION
**Pull request by mraible**
We used to use this, but haven't in a couple years.

### CODE REVIEW

**Review by aarongranick-okta — APPROVED** [review]

**Review by shuowu — APPROVED** [review]

**Comment by aarongranick-okta** [comment]
Thanks @mraible we'll get this change in

**Comment by arvindkrishnakumar-okta** [comment]
@aarongranick-okta can you merge this? I do not have the permissions.

**Comment by shuowu** [comment]
The change is in master now, close this PR.

**Comment by aarongranick-okta** [comment]
Change was merged in: https://github.com/okta/okta-angular/commit/c264fd53ecd0f17dc60b787eaa546c66a6cb05a6#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R79

Thanks gain, @mraible !

**Pull request closed without merging**
